apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend-service"
  labels:
    app: backend
spec:
  type: ClusterIP  # Internal cluster communication only
  selector:
    app: backend   # This MUST match the labels on your Backend Pods
  ports:
    - protocol: TCP
      port: 80         # The port other apps inside the cluster will target
      targetPort: {{ .Values.backend.port }}  # The actual port FastAPI listens on (8000)